version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run Python Script
          command: python main.py

  test:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Run Tests
          command: python test.py

  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - run:
          name: Deploy
          command: echo "Practical done"

workflows:
  build_and_test_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: main
